services:

  api:

    build:
      context: .
      dockerfile: Dockerfile


    container_name: ordermanagement-api


    ports:
      - "8080:8080"


    environment:

      ASPNETCORE_ENVIRONMENT: Development


      ConnectionStrings__DefaultConnection:
        Data Source=/app/database/orders.db


    volumes:

      - orders_database:/app/database


volumes:

  orders_database: